# Generated by Django 5.1 on 2024-11-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
