# Generated by Django 5.1 on 2024-11-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_node_is_parent_node_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parent_id',
            field=models.TextField(blank=True),
        ),
    ]
