# Generated by Django 5.1 on 2024-11-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_node_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parent_id',
            field=models.TextField(blank=True, default='0'),
        ),
    ]
