# Generated by Django 5.1 on 2024-11-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_node_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent_id',
        ),
    ]
